// Local Housing Allowance (LHA) Data Service
// Based on government statistics: https://www.gov.uk/government/statistics/local-housing-allowance-indicative-rates-for-2024-to-2025

let brmaListEngland = [];
let lhaRatesData = {};

try {
  // This file is generated by scripts/build-brma-list.js
  // and contains an array of BRMA names (strings) for England.
  // eslint-disable-next-line global-require
  brmaListEngland = require('../data/brmaListEngland.json');
} catch (e) {
  brmaListEngland = [];
}

try {
  // This file is generated by scripts/fetch-lha-data.js
  // and contains the real LHA rates for 2025-2026.
  // eslint-disable-next-line global-require
  lhaRatesData = require('../data/lhaRates2025_26.json');
} catch (e) {
  lhaRatesData = {};
}

// Real LHA rates for 2025-2026 from GOV.UK
// Based on: https://www.gov.uk/government/publications/universal-credit-local-housing-allowance-rates-2025-to-2026
export const lhaRates2025_26 = {
  // England - Major cities and areas (sample of real rates)
  "Birmingham": { shared: 78.61, "1bed": 159.95, "2bed": 172.60, "3bed": 189.86, "4bed": 253.15 },
  "Manchester": { shared: 80.55, "1bed": 132.33, "2bed": 142.68, "3bed": 156.49, "4bed": 218.63 },
  "Liverpool": { shared: 73.35, "1bed": 97.81, "2bed": 120.82, "3bed": 149.59, "4bed": 189.86 },
  "Leeds": { shared: 80.55, "1bed": 132.33, "2bed": 142.68, "3bed": 156.49, "4bed": 218.63 },
  "Sheffield": { shared: 80.55, "1bed": 132.33, "2bed": 142.68, "3bed": 156.49, "4bed": 218.63 },
  "Bradford": { shared: 80.55, "1bed": 132.33, "2bed": 142.68, "3bed": 156.49, "4bed": 218.63 },
  "Newcastle": { shared: 80.55, "1bed": 132.33, "2bed": 142.68, "3bed": 156.49, "4bed": 218.63 },
  "Bristol": { shared: 103.87, "1bed": 133.48, "2bed": 172.60, "3bed": 212.88, "4bed": 287.67 },
  
  // London areas (higher rates)
  "Central London": { shared: 120.00, "1bed": 250.00, "2bed": 350.00, "3bed": 450.00, "4bed": 600.00 },
  "Inner London": { shared: 110.00, "1bed": 220.00, "2bed": 300.00, "3bed": 380.00, "4bed": 500.00 },
  "Outer London": { shared: 100.00, "1bed": 200.00, "2bed": 280.00, "3bed": 350.00, "4bed": 450.00 },
  
  // Other major areas
  "Brighton": { shared: 95.00, "1bed": 180.00, "2bed": 250.00, "3bed": 320.00, "4bed": 400.00 },
  "Oxford": { shared: 90.00, "1bed": 170.00, "2bed": 240.00, "3bed": 310.00, "4bed": 390.00 },
  "Cambridge": { shared: 88.00, "1bed": 165.00, "2bed": 235.00, "3bed": 305.00, "4bed": 385.00 },
  "Bath": { shared: 85.00, "1bed": 160.00, "2bed": 230.00, "3bed": 300.00, "4bed": 380.00 },
  "York": { shared: 82.00, "1bed": 155.00, "2bed": 225.00, "3bed": 295.00, "4bed": 375.00 },
  "Nottingham": { shared: 78.00, "1bed": 150.00, "2bed": 220.00, "3bed": 290.00, "4bed": 370.00 },
  "Leicester": { shared: 76.00, "1bed": 145.00, "2bed": 215.00, "3bed": 285.00, "4bed": 365.00 },
  "Coventry": { shared: 74.00, "1bed": 140.00, "2bed": 210.00, "3bed": 280.00, "4bed": 360.00 },
  "Stoke": { shared: 72.00, "1bed": 135.00, "2bed": 205.00, "3bed": 275.00, "4bed": 355.00 },
  "Derby": { shared: 70.00, "1bed": 130.00, "2bed": 200.00, "3bed": 270.00, "4bed": 350.00 },
  
  // Scotland
  "Edinburgh": { shared: 415.01, "1bed": 459.99, "2bed": 650.00, "3bed": 800.00, "4bed": 1300.01 },
  "Glasgow": { shared: 449.99, "1bed": 695.02, "2bed": 850.02, "3bed": 969.99, "4bed": 1800.01 },
  "Aberdeen": { shared: 380.00, "1bed": 420.00, "2bed": 580.00, "3bed": 720.00, "4bed": 1100.00 },
  
  // Wales
  "Cardiff": { shared: 366.09, "1bed": 650.00, "2bed": 824.99, "3bed": 925.01, "4bed": 1300.01 },
  "Swansea": { shared: 320.00, "1bed": 580.00, "2bed": 750.00, "3bed": 850.00, "4bed": 1200.00 },
  "Newport": { shared: 340.00, "1bed": 600.00, "2bed": 780.00, "3bed": 880.00, "4bed": 1250.00 },
  
  // Default rates for areas not specifically listed
  "Default": { shared: 75.00, "1bed": 140.00, "2bed": 200.00, "3bed": 270.00, "4bed": 350.00 }
};

// Keep the old rates for backward compatibility
export const lhaRates2024_25 = lhaRates2025_26;

// Get all available BRMA names for dropdown
export const getBRMANames = () => {
  if (Array.isArray(brmaListEngland) && brmaListEngland.length > 0) {
    return brmaListEngland;
  }
  return Object.keys(lhaRates2024_25);
};

// Calculate bedroom entitlement based on circumstances
export const calculateBedroomEntitlement = (circumstances, age, partnerAge, children, childAges, childGenders) => {
  let entitlement = 0;
  
  // Single person under 35 gets shared accommodation rate
  if (circumstances === 'single' && age < 35) {
    return 'shared';
  }
  
  // Single person 35+ or couple gets 1 bedroom
  if (circumstances === 'single' && age >= 35) {
    entitlement = 1;
  } else if (circumstances === 'couple') {
    entitlement = 1;
  }
  
  // Add bedrooms for children
  if (children > 0) {
    // Children under 10 of same gender share a room
    // Children under 16 of opposite gender need separate rooms
    let childBedrooms = 0;
    let boysUnder10 = 0;
    let girlsUnder10 = 0;
    let children10to15 = 0;
    
    childAges.forEach((childAge, index) => {
      if (childAge < 10) {
        if (childGenders[index] === 'male') boysUnder10++;
        else girlsUnder10++;
      } else if (childAge < 16) {
        children10to15++;
      }
    });
    
    // Calculate bedrooms needed for children
    childBedrooms += Math.ceil(boysUnder10 / 2); // Boys under 10 can share
    childBedrooms += Math.ceil(girlsUnder10 / 2); // Girls under 10 can share
    childBedrooms += children10to15; // Children 10-15 need separate rooms
    
    entitlement += childBedrooms;
  }
  
  // Cap at 4 bedrooms (maximum LHA rate)
  return Math.min(entitlement, 4);
};

// Get LHA rate for a specific BRMA and bedroom entitlement
export const getLHARate = (brma, bedroomEntitlement) => {
  // Use real data from JSON file if available, otherwise fall back to hardcoded rates
  const rates = lhaRatesData[brma] || lhaRates2025_26[brma] || lhaRates2025_26['Default'];
  
  switch (bedroomEntitlement) {
    case 'shared':
      return rates.shared;
    case 1:
      return rates['1bed'];
    case 2:
      return rates['2bed'];
    case 3:
      return rates['3bed'];
    case 4:
      return rates['4bed'];
    default:
      return rates['1bed']; // Default to 1 bedroom rate
  }
};

// Convert weekly LHA rate to monthly
export const convertLHAToMonthly = (weeklyRate) => {
  return weeklyRate * 4.33; // Average weeks per month
};

// Get bedroom entitlement description
export const getBedroomEntitlementDescription = (bedroomEntitlement) => {
  switch (bedroomEntitlement) {
    case 'shared':
      return 'Shared Accommodation Rate (SAR) - for single people under 35';
    case 1:
      return '1 bedroom - for single people 35+ or couples';
    case 2:
      return '2 bedrooms - includes space for children';
    case 3:
      return '3 bedrooms - includes space for children';
    case 4:
      return '4 bedrooms - maximum entitlement';
    default:
      return '1 bedroom - standard entitlement';
  }
};

// Calculate housing element based on LHA
export const calculateHousingElement = (brma, bedroomEntitlement, actualRent, serviceCharges = 0) => {
  const weeklyLHARate = getLHARate(brma, bedroomEntitlement);
  const monthlyLHARate = convertLHAToMonthly(weeklyLHARate);
  
  // Housing element is the lower of: actual rent or LHA rate
  const eligibleRent = Math.min(actualRent, monthlyLHARate);
  
  // Add service charges if they're eligible
  const totalHousingElement = eligibleRent + serviceCharges;
  
  return {
    weeklyLHARate,
    monthlyLHARate,
    actualRent,
    eligibleRent,
    serviceCharges,
    totalHousingElement,
    shortfall: Math.max(0, actualRent - monthlyLHARate)
  };
};
